language: node_js
services:
  - mongodb
 node_js: 
  - "10" 
before_script: 
  - mongo testBooks --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - cd backend
  - npm install mocha chai
  - npm run test
  - cd ..
  - cd frontend
  - npm install enzyme
script:
  - npm run test
