language: node_js
services:
  - mongodb
 node_js: 
  - "10" 
before_script: 
  - cd backend
  - npm install mocha chai
  - npm run test
  - cd ..
  - cd frontend
  - npm install enzyme
script:
  - npm run test
